version: '3'
services:
  srv:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - ./usr_local_bunlde:/usr/local/bundle
    working_dir: /src/myapp
    command: rails s -p 3000 -b '0.0.0.0'
    tty: true
